---
version: '3'
services:
  redis:
    image: redis

  app:
    depends_on: ['redis']
    #build: .
    image: foo
    environment:
      PLETH_ROOT: photos
      PLETH_REDIS: redis:6379
    volumes:
      - /store1/photos:/app/photos:ro
      - ./lib:/app/lib

  web:
    depends_on: ['app']
    image: nginx
    ports: ['8880:80']
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/share/nginx/html
      - /store1/photos:/usr/share/nginx/html/photos:ro
